// All action types in one place. Single source of truth.

export const ACTIONS = {
  LOAD: "LOAD",
  RESET_RUN: "RESET_RUN",
  PRESTIGE: "PRESTIGE",

  GATHER: "GATHER",
  BUILD: "BUILD",
  RESEARCH: "RESEARCH",
  CRAFT_TOOL: "CRAFT_TOOL",
  HUNT: "HUNT",

  EAT: "EAT",
  DRINK: "DRINK",
  REST: "REST",

  TICK: "TICK",
  RESPOND_TO_EVENT: "RESPOND_TO_EVENT",
  SYNC_MUSIC_UNLOCKS: "SYNC_MUSIC_UNLOCKS",

  MARK_SPLASH_SEEN: "MARK_SPLASH_SEEN",
  CLEAR_LOG: "CLEAR_LOG",

  // Dev / debug
  DEV_PATCH: "DEV_PATCH",
};
